{% set name = "csmapi" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/swigcsm/archive/{{ version }}.tar.gz
  sha256: 999fb2d0a9e5c5d95ecded4368aa14a3894d98c18f42e908d7d5cef3bb3c8ecd

build:
  number: 2
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - swig
    - python
  host:
    - csm
    - python
    - setuptools
  run:
    - csm
    - python

test:
  imports:
    - csmapi

about:
  home: http://github.com/USGS-Astrogeology/swigcsm
  license: Public Domain
  license_file: LICENSE.txt
  summary: Swig generated Python bindings to the Community Sensor Model API

extra:
  recipe-maintainers:
    - jlaura
    - kelvinrr
    - jessemapel
