travis:
  secure:
    BINSTAR_TOKEN: wKf+kLgFImnAq/RC8uyS3vHW08F5CdtoAUmbulFl3uaRZNJCUZfBNXML2Suj2kFj3v0uXiiyMgwmps2PWynwC7/pKFh4ohT89zD9A40oD+wYW0BwGI/k7DnlX37bvpafubDEuasI8Iu7s1+Crqd7vOo79IMXhZmPdL10CM7tYVnwpMmOoyEQNUXFEV4Qibb0yNe7W0uqkFL1i54mAmY+K9/a8+MoOTB6NXjswnuePpS+8RMCVmPRadT773iXuMWU8cVLyfSytSNlMRNRvsK2a2tJC45sF5pMPKrzWbkQSRuuwqoTp5BHaZhfsY+RcYNs2I2QDr+7rpT5FSMCM957/DSNKW4ZXJ6EI+puOrZEIxERjB/A+dh1vJUd8r+aZQZw4WrXaOPU1MD4N3OGiNhuramreEgTdsxPaCV2yea9HQm+WtXn4jM/6iOQQfka+h2CLP2PAMuJ+gp/DqHjc+DwcXxNllSLQAk9q5CzXg6pc/6tI5XWdYp7ySVVXOxsyQhUl0G0dWU3oBwRwBGf7T0te/lWhTH0kN5jswjDtv6kiW1XMDLQc19WodhkMErtrMO0OtDAfoCYluuuWYtxzpNCCzpI230JrdQstvN4of+6jKST8gWJrq5PgIf9fm3tDd75zm27fKFnODzUw5vHTKBj/nIxeDR7XuzI/azzRvE7PXw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

min_py_ver: '35'
